/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primary Colors
        primary: {
          1000: '#ff9c1f',
          900: '#fea900',
          800: '#ff8513',
          700: '#ff6310',
          600: '#dc4c1c',
          500: '#ffec74',
          400: '#fff8c8',
        },
        // Secondary Colors
        secondary: {
          1000: '#0a0a0a',
          900: '#252525',
          800: '#5a5a5a',
          700: '#787878',
          600: '#b5b5b5',
          500: '#d9d9d9',
          400: '#f8f8f8',
          300: '#fefefe',
        },
        // Background Colors
        background: '#fefefe',
        'background-secondary': '#f8f8f8',
      },
      fontSize: {
        // Main Typography
        'main-title': ['2rem', { lineHeight: '3rem', fontWeight: '600' }],
        'heading-large': ['2.3rem', { lineHeight: 'normal', fontWeight: '700' }],
        'heading-medium': ['2rem', { lineHeight: '3rem', fontWeight: '500' }],
        'body-large': ['1.4rem', { lineHeight: 'normal', fontWeight: '600' }],
        'body-medium': ['1.2rem', { lineHeight: 'normal', fontWeight: '500' }],
        'body-secondary': ['1.4rem', { lineHeight: 'normal', fontWeight: '500' }],
        'caption-bold': ['1rem', { lineHeight: '1.1rem', fontWeight: '600' }],
        'body-bold': ['1.6rem', { lineHeight: 'normal', fontWeight: '600' }],
        'body-small-bold': ['1.2rem', { lineHeight: 'normal', fontWeight: '600' }],
        'body-small-regular': ['1.2rem', { lineHeight: 'normal', fontWeight: '400' }],
        'accent-bold': ['1.4rem', { lineHeight: 'normal', fontWeight: '600' }],
        'accent-large': ['2.4rem', { lineHeight: '3.6rem', fontWeight: '600' }],
        'accent-medium': ['2.16rem', { lineHeight: '3.6rem', fontWeight: '500' }],
        'white-bold': ['1.8rem', { lineHeight: 'normal', fontWeight: '600' }],
        'white-large': ['2.8rem', { lineHeight: 'normal', fontWeight: '600' }],
        'orange-medium': ['1.1rem', { lineHeight: 'normal', fontWeight: '500' }],

        // Legacy (기존 호환성)
        heading1: ['3.3rem', { lineHeight: '2.8rem', fontWeight: '600' }],
        heading2: ['2.7rem', { lineHeight: '2.3rem', fontWeight: '700' }],
        heading3: ['2.7rem', { lineHeight: '2.3rem', fontWeight: '600' }],
        heading4: ['3rem', { lineHeight: '2rem', fontWeight: '600' }],
        heading5: ['2.4rem', { lineHeight: '2rem', fontWeight: '600' }],
        body1: ['2rem', { lineHeight: '3rem', fontWeight: '500' }],
        body2: ['1.9rem', { lineHeight: '1.6rem', fontWeight: '600' }],
        body3: ['1.9rem', { lineHeight: '1.6rem', fontWeight: '500' }],
        body4: ['3rem', { lineHeight: '1.4rem', fontWeight: '500' }],
        body5: ['1.7rem', { lineHeight: '1.4rem', fontWeight: '600' }],
        body6: ['1.7rem', { lineHeight: '1.4rem', fontWeight: '500' }],
        body7: ['1.6rem', { lineHeight: '1.3rem', fontWeight: '600' }],
        body8: ['1.6rem', { lineHeight: '1.3rem', fontWeight: '400' }],
        body9: ['1.4rem', { lineHeight: '1.2rem', fontWeight: '600' }],
        body10: ['1.4rem', { lineHeight: '1.2rem', fontWeight: '400' }],
        caption1: ['1.3rem', { lineHeight: '1.1rem', fontWeight: '600' }],
        caption2: ['1.3rem', { lineHeight: '1.1rem', fontWeight: '500' }],
        caption3: ['1.3rem', { lineHeight: '1.1rem', fontWeight: '400' }],
        caption4: ['1.2rem', { lineHeight: '1rem', fontWeight: '400' }],
      },
      fontFamily: {
        pretendard: ['Pretendard Variable', 'sans-serif'],
      },
      spacing: {
        4.7: '4.7rem',
        4.8: '4.8rem',
        4.9: '4.9rem',
        5.3: '5.3rem',
        6.6: '6.6rem',
        6.7: '6.7rem',
        8.3: '8.3rem',
        11.1: '11.1rem',
        16.1: '16.1rem',
      },
      borderRadius: {
        '1rem': '1rem',
        '2rem': '2rem',
        '3rem': '3rem',
      },
      zIndex: {
        header: '6',
        'bottom-nav': '8',
        'under-header-section': '5',
        modal: '7',
        'card-profile-1': '4',
        'card-profile-2': '3',
        'card-profile-3': '2',
        'card-profile-4': '1',
        'negative-1': '-1',
        'negative-5': '-5',
      },
    },
  },
  plugins: [],
};
